# Generated by Django 4.0.4 on 2022-06-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grottadelbeholder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classcontent',
            old_name='Skills',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='racecontent',
            old_name='abilities',
            new_name='subraces',
        ),
        migrations.RenameField(
            model_name='classcontent',
            old_name='abilities',
            new_name='traits',
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='armorProficiency',
            field=models.CharField(choices=[('N', 'Nessuna'), ('L', 'Armature leggere'), ('M', 'Armature medie'), ('A', 'Tutte le armature')], max_length=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('CL', 'Classi'), ('RA', 'Razze'), ('MO', 'Mostri'), ('SP', 'Incantesimi')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='spellcontent',
            name='school',
            field=models.CharField(choices=[('V', 'Evocazione'), ('I', 'Illusione'), ('C', 'Invocazione'), ('A', 'Abiurazione'), ('N', 'Necromanzia'), ('T', 'Trasmutazione'), ('E', 'Ammaliamento'), ('D', 'Divinazione')], default='V', max_length=1),
        ),
    ]
