# Generated by Django 4.0.4 on 2022-06-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grottadelbeholder', '0002_rename_skills_classcontent_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monstercontent',
            old_name='abilities',
            new_name='traits',
        ),
    ]
