# Generated by Django 4.0.4 on 2022-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grottadelbeholder', '0003_rename_abilities_monstercontent_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstercontent',
            name='speed',
            field=models.CharField(max_length=25),
        ),
    ]
